export enum Type {
  TEXT = 'text',
  EMAIL = 'email',
  ADDRESS = 'address',
  URL = 'url',
  NUMBER = 'number',
  PHONE = 'phone',
  PASSWORD = 'password',
  DATE = 'date',
  TIME = 'time',
  MULTIPLE_CHOICE = 'multipleChoice',
  DROPDOWN = 'dropdown',
  SLIDER = 'slider',
}

export enum Properties {
  REQUIRED = 'required',
  VISIBILITY_RULES = 'visibilityRules',
  VALIDATIONS = 'validations',
  DEFAULT_VALUE = 'defaultValue',
  PLACEHOLDER = 'placeholder',
  AMOUNT_LINES = 'amountLines',
  INTEGER = 'integer',
  PHONE_FORMAT = 'phoneFormat',
  DATES_PAST = 'datesPast',
  DATES_FUTURE = 'datesFuture',
  MULTIPLE_ANSWERS = 'multipleAnswers',
  OPTIONS = 'options',
  MIN_VALUE = 'minValue',
  MAX_VALUE = 'maxValue',
  STEP = 'step',
  HIDE_VALUE_LABEL = 'hideValueLabel',
  HIDE_MIN_MAX_LABELS = 'hideMinMaxLabels',
}
